/*!
 * Inter Application Communication 4.0 Client
 * @version 4.0.0
 * @author Peter Müller
 */
var nx=nx||{},JSON=JSON||{};nx.iac=nx.iac||{};(function(){function f(n){return n<10?"0"+n:n;}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null;};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf();
};}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,gap,indent,meta={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},rep;function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);
})+'"':'"'+string+'"';}function str(key,holder){var i,k,v,length,mind=gap,partial,value=holder[key];if(value&&typeof value==="object"&&typeof value.toJSON==="function"){value=value.toJSON(key);}if(typeof rep==="function"){value=rep.call(holder,key,value);}switch(typeof value){case"string":return quote(value);case"number":return isFinite(value)?String(value):"null";case"boolean":case"null":return String(value);case"object":if(!value){return"null";}gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;
for(i=0;i<length;i+=1){partial[i]=str(i,value)||"null";}v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";gap=mind;return v;}if(rep&&typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==="string"){v=str(k,value);if(v){partial.push(quote(k)+(gap?": ":":")+v);}}}}else{for(k in value){if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v){partial.push(quote(k)+(gap?": ":":")+v);}}}}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";
gap=mind;return v;}}if(typeof JSON.stringify!=="function"){JSON.stringify=function(value,replacer,space){var i;gap="";indent="";if(typeof space==="number"){for(i=0;i<space;i+=1){indent+=" ";}}else{if(typeof space==="string"){indent=space;}}rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number")){throw new Error("JSON.stringify");}return str("",{"":value});};}if(typeof JSON.parse!=="function"){JSON.parse=function(text,reviver){var j;function walk(holder,key){var k,v,value=holder[key];
if(value&&typeof value==="object"){for(k in value){if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined){value[k]=v;}else{delete value[k];}}}}return reviver.call(holder,key,value);}cx.lastIndex=0;if(cx.test(text)){text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4);});}if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");
return typeof reviver==="function"?walk({"":j},""):j;}throw new SyntaxError("JSON.parse");};}}());!(function(h,l,a){nx.iac.type={USECASE:1<<0,EVENT:1<<1,RPC:1<<2,RPE:1<<3,INTERN:1<<4,EXTERN:1<<5};function n(o){if(typeof o!=="number"){throw new b("Wrong data type for flags. flags must be numeric.","Use_case_wrong_flagged");}o=parseInt(o,10);if(nx.iac.type.USECASE&o&&nx.iac.type.EVENT&o){throw new b("You cannot flag a IAC message as USECASE and EVENT.","Use_case_wrong_flagged");}if(!(nx.iac.type.USECASE&o)&&!(nx.iac.type.EVENT&o)){throw new b("You must flag a IAC message as USECASE or EVENT","Use_case_wrong_flagged");
}if(nx.iac.type.RPC&o&&nx.iac.type.RPE&o){throw new b("You cannot flag a IAC message as RPC and RPE.","Use_case_wrong_flagged");}if(!(nx.iac.type.RPC&o)&&!(nx.iac.type.RPE&o)){throw new b("You must flag a IAC message as RPC or RPE","Use_case_wrong_flagged");}if(nx.iac.type.INTERN&o&&nx.iac.type.EXTERN&o){throw new b("You cannot flag a IAC message as INTERN and EXTERN.","Use_case_wrong_flagged");}if(!(nx.iac.type.INTERN&o)&&!(nx.iac.type.EXTERN&o)){throw new b("You must flag a IAC message as INTERN or EXTERN","Use_case_wrong_flagged");
}return o;}function j(q,p){var o=Array.prototype.slice(arguments,2);return function(){return q.apply(p,o.concat(Array.prototype.slice.call(arguments)));};}function b(o,p){this.name="IACError";this.message=[o,nx.iac.Debugger.enabled?("//wiki.intranet.1and1.com/bin/view/Ihapps/InterApplicationCommunication40Client#"+(p||"")):""].join("\r\n")||"An unknown IAC error occured";}b.prototype=Error.prototype;nx.iac.Debugger={enabled:false,name:location.host+""+location.pathname,hey:function(){if(this.enabled){this.log("IAC("+this.name+"): ");
}return this;},log:function(){try{if(this.enabled&&h.console&&h.console.log){h.console.log.apply(h.console,arguments);}}catch(o){}return this;},warn:function(){try{if(this.enabled&&h.console&&h.console.warn){h.console.warn.apply(h.console,arguments);}}catch(o){}return this;},debug:function(){try{if(this.enabled&&h.console&&h.console.debug){h.console.debug.apply(h.console,arguments);}}catch(o){}return this;}};function k(){this.onMessage=function(){};this.onInitialized=function(){};this.init=function(){throw new b("Missing abstract IACTransport::init() method.");
};this.initialized=function(){throw new b("Missing abstract IACTransport::initialized() method.");};this.send=function(o,p){throw new b("Missing abstract IACTransport::send() method.");};}k.prototype.incomingMessageFactory=function(p){var o,q=new d();q.setFlags(p.type);q.setName(p.usecase);q.setSender(p.sender);q.setPayload.apply(q,p.args);switch(true){case !!(nx.iac.type.USECASE&p.type):o=new g();break;case !!(nx.iac.type.EVENT&p.type):o=new i();break;default:throw new b("Invalid IAC message detected, which is not flagged as USECASE or EVENT.","Invalid_IAC_message_detected");
break;}o.protocol=q;o.transport=this;return o;};k.prototype.outgoingMessageFactory=function(o,p){return o;};function e(o){var q=o,p=false;this.init=function(){var r=j(this.onMessageWrapper,this);if(h.addEventListener){h.addEventListener("message",r,false);}else{h.attachEvent("onmessage",r);}p=true;this.onInitialized();};this.initialized=function(){return p;};this.onMessageWrapper=function(r){var s;try{s=JSON.parse(r.data);}catch(t){nx.iac.Debugger.hey().warn("Any unknownable post message protocol detected.");
}finally{if(s){this.onMessage(this.incomingMessageFactory(s));}}};this.send=function(r,t){var s=o;r=this.outgoingMessageFactory(r,t);(t?t.contentWindow:top).postMessage(JSON.stringify(r),"*");};}e.prototype=new k();e.prototype.constructor=k;function c(p){var t=p,r=false,q,u,o,v,s;this.init=function(){if(h.addEventListener){h.addEventListener("unload",x,false);}else{if(h.attachEvent){h.attachEvent("onunload",x);h.attachEvent("onbeforeunload",w);}}h.handleLocalConnectionInit=j(this.initLocalConnection,this);
h.handleLocalConnectionMessage=j(this.onMessageWrapper,this);if(!!t.flash_container){q=l.getElementById(t.flash_container);}else{q=l.getElementById("flash-fallback-container");}if(!q){q=l.createElement("div");q.id="flash-fallback-container";l.getElementsByTagName("body")[0].appendChild(q);}var y="//js.ui-portal.de/apps/navigator-common/iac/client/4.0.0/iac.swf";q.innerHTML=['<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="iac-local-connection-object" codebase="//fpdownload.macromedia.com/get/flashplayer/current/swflash.cab" width="1px" height="1px">','<param name="movie" value="'+y+'" />','<param name="allowScriptAccess" value="always" />','<embed id="iac-local-connection-embed" src="'+y+'" play="true" loop="false" allowScriptAccess="always" type="application/x-shockwave-flash" pluginspage="https://www.adobe.com/go/getflashplayer" width="1px" height="1px">',"</embed>","</object>"].join("");
u=l.getElementById("iac-local-connection-object");o=l.getElementById("iac-local-connection-embed");};this.initialized=function(){return r;};var w=function(){if(l.readyState=="interactive"){function y(){l.detachEvent("onstop",y);x();}l.attachEvent("onstop",y);h.setTimeout(function(){l.detachEvent("onstop",y);},0);}};var x=function(){try{if(v&&v.disconnect){v.disconnect();}}catch(y){}};this.initLocalConnection=function(){v=o||u;if(!v){if(!s){s=h.setInterval(j(function(){this.initLocalConnection();},this),100);
}return;}else{if(s){h.clearInterval(s);}}try{v.disconnect();}catch(z){}var y=v.connect(t.appname,t.context_token);r=true;this.onInitialized();};this.onMessageWrapper=function(B,y,A,z){try{B=JSON.parse(B);}catch(C){nx.iac.Debugger.hey().warn("Any unknownable post message protocol detected:");}finally{if(B){this.onMessage(this.incomingMessageFactory(B));}}y=null;A=null;z=null;};this.send=function(y,z){if(!z){z={iacAppname:"navigator"};}z.iacAppname=z.iacAppname?z.iacAppname:"navigator";y=this.outgoingMessageFactory(y,z);
v.sendMessage(z.iacAppname,z.iacAppname,JSON.stringify(y),"*");};}c.prototype=new k();c.prototype.constructor=k;function d(){var o={type:0,sender:"",usecase:"",args:[]};this.setFlags=function(p){o.type|=p;};this.getFlags=function(){return o.type;};this.unsetFlag=function(p){var q=-1;while(Math.pow(2,++q)!=p){}o.type&=~(1<<q);return this;};this.setSender=function(p){if(typeof p!=="string"){throw new b("Wrong data type for sender. sender must be a type of string.");}if(!p){throw new b("The sender cannot be empty.");
}o.sender=p;return this;};this.getSender=function(){return o.sender;};this.setName=function(p){if(typeof p!=="string"){throw new b("Wrong data type for name. name must be a type of string.","Invalid_Use_case_name");}if(!p){throw new b("The name cannot be empty.","Invalid_Use_case_name");}o.usecase=p;return this;};this.getName=function(){return o.usecase;};this.setPayload=function(){o.args=Array.prototype.slice.call(arguments);return this;};this.getPayload=function(){return o.args;};this.getRawData=function(){return o;
};}function m(o,p){this.protocol=o;this.transport=p;this.pending=true;this.send=function(q){if(q&&(typeof q!=="object"||!q.contentWindow||!q.iacAppname)){throw new b("No valid message target given.");}n(this.protocol.getFlags());if(!this.transport.initialized()){this.pending=true;}else{this.pending=false;this.transport.send(this.protocol.getRawData(),q);}return this;};this.isPending=function(){return !!this.pending;};this.setName=function(q){this.protocol.setName(q);return this;};this.getName=function(){return this.protocol.getName();
};this.getSender=function(){return this.protocol.getSender();};this.setPayload=function(){this.protocol.setPayload.apply(this.protocol,arguments);return this;};this.getPayload=function(){return this.protocol.getPayload();};}function g(){this.asRPE=function(){this.protocol.unsetFlag(nx.iac.type.RPC).setFlags(nx.iac.type.RPE);return this;};this.asRPC=function(){this.protocol.unsetFlag(nx.iac.type.RPE).setFlags(nx.iac.type.RPC);return this;};this.asIntern=function(){this.protocol.unsetFlag(nx.iac.type.EXTERN).setFlags(nx.iac.type.INTERN);
return this;};this.asExtern=function(){this.protocol.unsetFlag(nx.iac.type.INTERN).setFlags(nx.iac.type.EXTERN);return this;};}g.prototype=new m();g.prototype.constructor=m;function i(){}i.prototype=new m();i.prototype.constructor=m;var f=function(){var q,t,s,r=false,o=[],p=[];this.init=function(u){if(typeof u!=="object"){throw new b("init requires a plain configuration object.","Invalid_Initialization");}if(!u.appname){throw new b("No valid IAC appname given.","Invalid_Initialization");}if(!u.context_token){throw new b("No valid IAC token given.","Invalid_Initialization");
}q=u;this.listen(nx.iac.type.USECASE,"__connected__",function(){r=true;s();},this);this.listen(nx.iac.type.USECASE,"__disconnected__",function(){r=false;},this);if(typeof h.postMessage==="function"||typeof h.postMessage==="object"){t=new e(u);}else{t=new c(u);}t.onMessage=j(this.onMessage,this);t.onInitialized=this.sendPendingMessages;t.init();return this;};this.requiresInitialization=function(){if(!q){throw new b("IAC Client is not yet initialized.","Not_Initialized");}return this;};this.getAppname=function(){return q.appname||"unknown appname";
};this.connect=function(u){this.requiresInitialization();s=typeof u==="function"?u:function(){};this.createUsecase("__connect__").asRPE().send();return this;};this.disconnect=function(){this.requiresInitialization();this.createUsecase("__disconnect__").asRPE().send();return this;};this.isConnected=function(){this.requiresInitialization();return r;};this.connected=function(){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::connected(). Please use nx.iac.Client::isConnected() instead.");
return this.isConnected();};this.sendPendingMessages=function(){var v=0,u=p.length,w;for(;v<u;v++){w=p[v];if(w.isPending()){w.send();}}return this;};this.createUsecase=function(v,w){this.requiresInitialization();if(typeof v!=="string"||!v){throw new b("An IAC use case name must be a string and cannot be empty.","Invalid_Use_case_name");}var u=new g();u.protocol=new d();u.transport=t;u.protocol.setFlags(nx.iac.type.USECASE|nx.iac.type.RPC|nx.iac.type.INTERN);u.protocol.setSender(this.getAppname());
u.setName(v);u.setPayload(typeof w==="object"?w:{});p.push(u);return u;};this.listen=function(u,v,x,w){this.requiresInitialization();if(typeof u!=="number"){throw new b("Wrong data type for flags. flags must be numeric.","Use_case_wrong_flagged");}u=parseInt(u,10);if(typeof v!=="string"){throw new b("Wrong data type for name. name must be a type of string.","Invalid_Use_case_name");}if(!v){throw new b("The name cannot be empty.","Invalid_Use_case_name");}if(typeof x!=="function"){throw new b("No valid callback function given.","Missing_callback_function");
}o.push({flags:u||(nx.iac.type.USECASE|nx.iac.type.RPC|nx.iac.type.INTERN),name:v,callback:x,scope:w||x});return this;};this.onMessage=function(x){this.requiresInitialization();if(!(x instanceof g)&&!(x instanceof i)){throw new b("The message must be an instance of IACUsecase or IACEvent.");}var w=0,v=o.length,y,z,u;for(;w<v;w++){y=o[w];if(y.name==x.getName()){z=0;u=true;for(;z<32;z++){if((y.flags&(1<<z))&&(y.flags&(1<<z))!=(x.protocol.getFlags()&(1<<z))){u=false;}}if(u){y.callback.apply(y.scope,[x.getSender()].concat(x.getPayload()));
}}}return this;};this.invokeRPC=function(v){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::invokeRPC(). Please use nx.iac.Client::createUsecase() instead.");this.requiresInitialization();var u=new g();u.protocol=new d();u.transport=t;u.protocol.setFlags(nx.iac.type.USECASE|nx.iac.type.RPC|nx.iac.type.INTERN);u.protocol.setSender(this.getAppname());u.setName(v);u.setPayload.apply(u,Array.prototype.slice.call(arguments,1));p.push(u.send());return this;};this.invokeRPE=function(v){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::invokeRPE(). Please use nx.iac.Client::createUsecase() instead.");
this.requiresInitialization();var u=new g();u.protocol=new d();u.transport=t;u.protocol.setFlags(nx.iac.type.USECASE|nx.iac.type.RPE|nx.iac.type.INTERN);u.protocol.setSender(this.getAppname());u.setName(v);u.setPayload.apply(u,Array.prototype.slice.call(arguments,1));p.push(u.send());return this;};this.bindUsecase=function(u,v){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::bindUsecase(). Please use nx.iac.Client::listen() instead.");this.requiresInitialization();
this.listen(nx.iac.type.USECASE,u,v);return this;};this.unbindUsecase=function(x){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::unbindUsecase().");this.requiresInitialization();var w=0,u=o.length,v=[];for(;w<u;w++){if(o[w].name==x&&nx.iac.type.USECASE&o[w].flags){v.push(w);}}while(v.length){o.splice(v.pop(),1);}return this;};this.bindEvent=function(u,v){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::bindEvent(). Please use nx.iac.Client::listen() instead.");
this.requiresInitialization();this.listen(nx.iac.type.EVENT,u,v);return this;};this.unbindEvent=function(x){nx.iac.Debugger.hey().warn("You are using a the deprecated function nx.iac.Client::unbindEvent().");this.requiresInitialization();var w=0,u=o.length,v=[];for(;w<u;w++){if(o[w].name==x&&o[w].flags&nx.iac.type.EVENT){v.push(w);}}while(v.length){o.splice(v.pop(),1);}return this;};};nx.iac.Client=new f();f.prototype.reinitializeApplication=function(){this.createUsecase("reinitialize_application").send();
return this;};f.prototype.reinitializeNavigator=function(o){this.createUsecase("reinitialize_navigator",o).send();return this;};f.prototype.logoutNavigator=function(){this.createUsecase("logout_navigator").send();return this;};f.prototype.openGotoFeature=function(o){this.createUsecase("open_goto_feature",o).send();return this;};f.prototype.openFeedbackDialog=function(){this.createUsecase("open_feedback_dialog").send();return this;};f.prototype.disableNavigator=function(){this.createUsecase("disable_navigator").send();
return this;};f.prototype.enableNavigator=function(){this.createUsecase("enable_navigator").send();return this;};f.prototype.hideNavigator=function(){this.createUsecase("hide_navigator").send();return this;};f.prototype.showNavigator=function(){this.createUsecase("show_navigator").send();return this;};f.prototype.track=function(o){this.createUsecase("tracking_track",o).asRPE().send();return this;};}(window,document));